### ISSUE TITLE
Resource Temporarily Unavailable

### ISSUE THREAD

**Issue by WadeLovell** [udacity/cloud-developer#142]
I have gotten this in attempting to clone repositories today. I am on the latest version of GitHub Desktop. I have tried launching Desktop from GitHub as well as pasting the URL into Desktop with the same results.

unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\succe.I7DESKTOP\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (22048) C:\Users\succe.I7DESKTOP\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1301408/0x1331408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15408498 [main] sh 674 dofork: child -1 - forked process 22048 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\succe.I7DESKTOP\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by SudKul** [comment]
Seems like a temporary issue from the Github platform.
