### ISSUE TITLE
Merge 3rd module's exercises and project code

### ISSUE THREAD

**Issue by mnfgul** [udacity/cloud-developer#16]
It will be great if you can add code for exercises from https://github.com/scheeles/cloud-developer/tree/01-start/course-03/

**Comment by nikhilgy** [comment]
Can you help me with the Full Stack App on AWS project .

**Comment by SudKul** [comment]
Scheeles course in the Cloud Developer ND9990 nanodegree had become deprecated in 2020. 
So, we no more need to include the https://github.com/scheeles/cloud-developer/tree/01-start/course-03/ content into the current repo. 

Closing this issue.
