### ISSUE TITLE
Add Postman collection for demos of C4 demos and exercises.

### ISSUE THREAD

**Issue by floriansalihovic** [udacity/cloud-developer#17]
Postman collection is missing to test the REST API.

It is not the collection for the final project, but the Image sharing project.

**Comment by IvanBila** [comment]
Hi @floriansalihovic this issue was addressed here https://github.com/udacity/cloud-developer/commit/0864589b1aa01330dfedabc43912c387aba8dc53

**Comment by SudKul** [comment]
Hope the [0864589](https://github.com/udacity/cloud-developer/commit/0864589b1aa01330dfedabc43912c387aba8dc53) commit has addressed the request.
