### ISSUE TITLE
Error code of Elifecycle

### ISSUE THREAD

**Issue by Berryakin2010** [udacity/cloud-developer#222]
"npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! udacity-c2-basic-server@1.0.0 dev: `ts-node-dev --respawn --transpileOnly ./src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the udacity-c2-basic-server@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above."

Has anyone seen this before and what are the common solutions?  I was worried it had to do with laptop RAM based on the first line of error code, but there seems to be more.  Any help would be greatly appeciated.

**Comment by SudKul** [comment]
Closing this issues, as it seems to be user-specific. 
The future learners must utilise the https://knowledge.udacity.com/ for individual-specific errors, and take help from mentors directly.
