### ISSUE TITLE
Missing Data folder

### ISSUE THREAD

**Issue by Berryakin2010** [udacity/cloud-developer#223]
I don't see in the repository "sequelize-typescript" and it has caused an error message in Visual Studio.

import {Sequelize} from 'sequelize-typescript';
import { config } from './config/config';

**Comment by Berryakin2010** [comment]
Found it.  It was in a completely different location.  We import it from Sequilize section of the course (Lesson 4).

**Comment by SudKul** [comment]
Hi @Berryakin2010 
Apologies for a delayed response. 
Would you like to submit a PR to help us keep the starter code updated?
Thank you
