### ISSUE TITLE
Fix tslint config

### ISSUE THREAD

**Issue by goatfryed** [udacity/cloud-developer#224]
There are several issues with the tslint config provided in the projects. Atleast for c2 restapi & frontend.

* The rules directory codelyzer does not exist and fails the build.
* There is a mix of ' and " quotes in the project. " are used in config files, ' mostly in code. The current tslint config treats this as error
* c2 restapi specific
** can't run build in lesson 4, part 7, because authentication isn't handled yet and implicit any is used.

I suggest to use a more relaxed tslint config...

**Comment by valentinpalkovic** [comment]
Or to throw tslint completely away, because it is deprecated. Are PR requests and proposed changes welcome? I would like to throw tslint away and replace it through eslint

**Comment by SudKul** [comment]
Hi @valentinpalkovic 
Apologies for a delayed response. We have started cleaning up the repos recently. 
Yes, we would be delighted to have the PRs with enhancements/code-upgrades. 
Thank you.
