### ISSUE TITLE
API exercise package.json with wrong entry point

### ISSUE THREAD

**Issue by samuelchvez** [udacity/cloud-developer#271]
Should be `"main": "server.js"` instead of `"main": "src/server.js"`. Elastic Beanstalk won't put the instance as healthy without this change.

**Comment by technolytic** [comment]
Same here.
Thanks!

**Comment by ShibbyG** [comment]
Same here too. Thanks

**Comment by fxrcode** [comment]
I had fix in my repo: https://github.com/fxrcode/Udacity-Cloud-Developer/blob/main/course-02/exercises/udacity-c2-restapi/package.json

**Comment by SudKul** [comment]
Done in Udacity repo. See here: https://github.com/udacity/cloud-developer/blob/master/course-02/exercises/udacity-c2-restapi/package.json
