### ISSUE TITLE
API exercise jwt payload should be a plain object

### ISSUE THREAD

**Issue by samuelchvez** [udacity/cloud-developer#273]
Found that jwt library expects the payload to be a plain object. As seen in the course, we send directly the sequelize model instance, which is not a plain object. To solve it, I used the method `short()` inside the `generateJWT` method:

```
function generateJWT(user: User): string {
    return jwt.sign(user.short(), config.jwt.secret);
}
```

**Comment by SudKul** [comment]
Hi @samuelchvez 
Would you mind submitting a PR for a quick turnaround?
I can see that there are relevant [Knowledgehub](https://knowledge.udacity.com/questions/76262) discussions around the topic.  
Thanks

**Comment by SudKul** [comment]
Relates to https://github.com/udacity/cloud-developer/issues/50 and https://knowledge.udacity.com/questions/76262

**Comment by SudKul** [comment]
Fixed in this commit https://github.com/udacity/cloud-developer/commit/916b6f41a38d08759b5dbb1e0634db8cc8ccedc8
