### ISSUE TITLE
S3 CORS confg is missing

### ISSUE THREAD

**Issue by Omnyyah** [udacity/cloud-developer#33]
Hi,

it looks like the S3_CORS.xml file is missing in the basic server folder.

thank you!

**Comment by chrisbvt** [comment]
Although I wouldn't highly suggest copy pasting other people's unverified code here's the S3_CORS.xml written up for this: 

`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
`

**Comment by melanievillela** [comment]
This helped me: 

[https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html]
