### ISSUE TITLE
SQL Injection vulnerability

### ISSUE THREAD

**Issue by wfs** [udacity/cloud-developer#44]
Hi Gabe, ran "npm install" and received "found 1 high severity vulnerability".

"npm audit" gives link "https://www.npmjs.com/advisories/1146" and recommends package.json updated from "sequelize": "^5.10.0" to "sequelize": "^5.15.1".

Re-running "npm install" resolves issue with "found 0 vulnerabilities".

**Comment by ggmartins** [comment]
@wfs do you mean running "npm audit fix" before re running "npm install"?

**Comment by SudKul** [comment]
Sure, we will update the dependencies to resolve the vulnerabilities. 
Meanwhile, we encourage you to submit a PR.
