### ISSUE TITLE
there have 3 bugs from auth.router.ts file on REST-API folder 

### ISSUE THREAD

**Issue by wiroger9595** [udacity/cloud-developer#47]
there have error message 

Represents the completion of an asynchronous operation Represents the completion of an asynchronous operation

A function whose declared type is neither 'void' nor 'any' must return a value.ts(2355)

**Comment by sniop** [comment]
I am getting following errors as well , is anyone looking into this?
src/controllers/v0/users/routes/auth.router.ts:13:61 - error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.

13 async function generatePassword(plainTextPassword: string): Promise<string> {
                                                               ~~~~~~~~~~~~~~~

src/controllers/v0/users/routes/auth.router.ts:17:75 - error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.

17 async function comparePasswords(plainTextPassword: string, hash: string): Promise<boolean> {
                                                                             ~~~~~~~~~~~~~~~~

src/controllers/v0/users/routes/auth.router.ts:21:35 - error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.

21 function generateJWT(user: User): string {

**Comment by sniop** [comment]
only had to add some empty return statements , for that to work

**Comment by mareksl** [comment]
You can add `// @ts-ignore` to ignore an error from the next line in the tsc compiler. Just remember to remove it afterwards, once you implement the function.

**Comment by fanyui** [comment]
You should edit those function to provide return statements that match the  expected return type 
ie return a promise that resolves to a string and another one that resolves to a boolean that should get rid of the errors.

**Comment by darkphoenix17** [comment]
The boilerplate code should have provided an empty return statement for those who are new to this or else
should have added a comment for students to fix this as a #todo to understand that promise return-type should return a value when the function is not void I found myself stuck in this and had to do lots of research as I am new to this language. 
Just a suggestion.
