### ISSUE TITLE
Creating GET function for id error server.ts

### ISSUE THREAD

**Issue by MiiriBrian** [udacity/cloud-developer#490]
While trying to create the Get function for id i am met with this error
![error ts](https://user-images.githubusercontent.com/30987068/184244940-a4dadf5f-45eb-42e3-899f-36f4a2453acf.PNG)

**Comment by MiiriBrian** [comment]
> While trying to create the Get function for id i am met with this error ![error ts](https://user-images.githubusercontent.com/30987068/184244940-a4dadf5f-45eb-42e3-899f-36f4a2453acf.PNG)

Im guessing its trying to read the let {id} as a string?

**Comment by SudKul** [comment]
Hey @MiiriBrian 
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors. Your discussion will help other learners who may have similar issues.
