### ISSUE TITLE
Bug in createImage.ts - missing conversion of the SIGNED_URL_EXPIRATION String to Number

### ISSUE THREAD

**Issue by aleks-dev** [udacity/cloud-developer#72]
This causes a hidden Lambda-code exception which I found via testing the [CreateImage code ](https://github.com/udacity/cloud-developer/blob/master/course-04/exercises/lesson-4/solution/src/lambda/http/createImage.ts) from the API Gateway console. 

**This**
`const urlExpiration = process.env.SIGNED_URL_EXPIRATION`

**should be updated to this**
`const urlExpiration = Number(process.env.SIGNED_URL_EXPIRATION)`

**Comment by SudKul** [comment]
Done in this commit:
https://github.com/udacity/cloud-developer/commit/dd58fa2f9b76b95233d302de0cab0165dff22a1d
