### ISSUE TITLE
The image used for testing under course 2 project is not available

### ISSUE THREAD

**Issue by lu-moreira** [udacity/cloud-developer#76]
Image URL used: https://timedotcom.files.wordpress.com/2019/03/kitten-report.jpg

![image](https://user-images.githubusercontent.com/45040629/73609760-9afbad80-45af-11ea-9fa3-7220c410a05c.png)

Maybe then could use another image to validate the course project?

**Comment by learnitmyway** [comment]
I would like to add: This was the link given in the [project rubric](https://review.udacity.com/#!/rubrics/2555/view)

**Comment by y0n1** [comment]
Moreover thanks to this link I found a bug in the `util.filterImageFromURL` function.
If the Jimp library fails to read the image from the given URL [original code](https://github.com/udacity/cloud-developer/blob/59fe409fac18159a311064eb579aae8a8d2c09ff/course-02/project/image-filter-starter-code/src/util/util.ts#L13)

**Comment by isidrolo80** [comment]
Also noticed it wasn't working. Any other public image URL should do the trick. My code includes verification if it's an image and the URL includes a ".jpeg | .gif | .png" extension so I would personally use public images with the file extension included.

**Comment by SudKul** [comment]
You can use any public image for this project/exercise, such as:
https://upload.wikimedia.org/wikipedia/commons/b/bd/Golden_tabby_and_white_kitten_n01.jpg
